In [2]:
import numpy as np

## Basics of Numpy

In [5]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get Dimension
b.ndim

2

In [11]:
# Get Shape
b.shape

(2, 3)

In [19]:
# Get Type
a.dtype

dtype('int64')

In [12]:
# Get Size
a.itemsize

8

In [21]:
# Get total size
#a.size * a.itemsize
a.nbytes

24

## Accessing/Changing specific elements, rows, columns, etc

In [15]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# Get a specific element [row, column]
a[1, 5]

13

In [16]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# Get a specific column
a[ :, 2]

array([ 3, 10])

In [26]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [27]:
# Changing an item
a[1, 5] = 20
print(a)

a[:,2] = 5
print(a)

a[:,2] = [1, 2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


* 3D example

In [18]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
# Get specific element (work outside in)
c = b[0, 1, 1]
print(c)

b[:, 0, :]

4


array([[1, 2],
       [5, 6]])

In [30]:
# Replace
b[:, 1, :] = [[9, 9],[8, 8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different Types of Arrays

In [31]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [34]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [35]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [36]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [38]:
# Random decimal numbers
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
np.random.rand(4, 2, 3)

array([[[0.48926616, 0.82881376, 0.86910666],
        [0.6950074 , 0.52767076, 0.63901102]],

       [[0.46861953, 0.89214406, 0.70776603],
        [0.29854123, 0.94597195, 0.42075173]],

       [[0.92101517, 0.53787055, 0.26951867],
        [0.85240439, 0.72268205, 0.51203356]],

       [[0.46985875, 0.45767338, 0.22181869],
        [0.4306932 , 0.66949089, 0.12833826]]])

In [39]:
# Return random floats in the half-open interval [0.0, 1.0)
np.random.random_sample(a.shape)

array([[0.67564972, 0.88589842, 0.87450182, 0.15710881, 0.71482004,
        0.92374945, 0.96790789],
       [0.07616817, 0.08987036, 0.74367598, 0.26563699, 0.1853076 ,
        0.90226272, 0.50696624]])

In [41]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[3, 4, 6],
       [3, 4, 6],
       [1, 5, 6]])

In [48]:
np.random.randint(-4, 7, size=(3,3))

array([[-1,  2,  0],
       [-2, -2, -3],
       [-1,  4,  3]])

In [52]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
# Repeating array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [59]:
# Q1

In [61]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:
z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [63]:
output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!

In [71]:
a = np.array([1, 2, 3])
b = a # points b is same as a (not copy)
b[0] = 100

print(a)

[100   2   3]


In [70]:
a = np.array([1, 2, 3])
b = a.copy() # this is copy
b[0] = 100

print(a)

[1 2 3]


## Mathematics

In [74]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [76]:
a + 2

array([3, 4, 5, 6])

In [77]:
a - 2

array([-1,  0,  1,  2])

In [79]:
a * 2

array([2, 4, 6, 8])

In [81]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [83]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [84]:
a ** 2

array([ 1,  4,  9, 16])

In [86]:
# Take sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [87]:
# Take cos of all values
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear Algebra

In [93]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [94]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [3]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.min(stats)

1

In [5]:
np.max(stats)

6

In [11]:
np.sum(stats)

21

## Reorganizing Arrays

In [14]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])